path-service: store/products
server:
  port: 8090
spring:
  application:
    name: store-product-service
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/store
    username: root
    password: root